api/urls.py
from django.urls import path
from api import views



app_name = "api"


urlpatterns = [
    path('v2/list/grantgoal/', views.GrantGoalAPIView.as_view(), name="api_list_grantgoal"),
    path('v2/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name="api_detail_grantgoal"),
    path('v2/create/grantgoal/', views.CreateGrantGoalAPIView.as_view(), name="api_create_grantgoal"),
    

    ##### URLS CLIENTS #####
    path('client/list/grantgoal/', views.ListGrantGoalClient.as_view(), name="clist_grantgoal"),
    path('client/create/grantgoal/', views.CreateGrantGoalClient.as_view(), name="ccreate_grantgoal"),
]

cplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

home/urls.py
from django.urls import path
from home import views



app_name = "home"


urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('logout/', views.LogOut.as_view(), name="logout"),
    path('user_profile/', views.CreateUserProfile.as_view(), name="user_profile"),
    path('detail/user_profile/<int:pk>/', views.DetailUserProfile.as_view(), name="detail_userprofile"),
    path('update/user_profile/<int:pk>/', views.UpdateUserProfile.as_view(), name="update_userprofile"),
    path('about/', views.About.as_view(), name="about"),    
    path('identity/', views.Identity.as_view(), name="identity"),
    path('contact/', views.Contact.as_view(), name="contact"),
]

home/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)
    bio = models.CharField(max_length=256, default="i Love This APP")
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, *args, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

home/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu username"}))
    password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu password"}))


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu username"}))
    password1 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu password"}))
    password2 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Repite tu password"}))
    email = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu email"}))
    first_name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu first_name"}))
    last_name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu last_name"}))
    class Meta:
        model = User
        fields = [
            "username",
            "password1",
            "password2",
            "email",
            "first_name",
            "last_name"
           
        ]
        # widgets = {
        #     "username": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu username"}),
        #     "password": forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu password"}),
        #     "email": forms.EmailInput(attrs={"type":"email", "class":"form-control", "placeholder":"Escribe tu email"})
        # }



class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            "user",
            "bio",
            "status"
        ]
        widgets = {
            "user": forms.Select(attrs={"type":"select", "class":"form-select"}),
            "bio": forms.Textarea(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe acerca de ti", "row":3}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox", "class":"form-checkbox"}),
        }

home/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse

from .forms import LoginForm, SignUpForm, UserProfileForm
from .models import UserProfile
# Create your views here.

class Index(generic.View):
    template_name = "home/index.html"
    context = {}
    form = LoginForm()

    def get(self, request):
        self.context = {
            "name": "Ray Parra",
            "lista": [1, 2, 3],
            "form": self.form
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            return redirect("/")

    

class LogOut(generic.View):
    def get(self, request):
        logout(request)
        return redirect("/")



class SignUp(generic.CreateView):
    template_name = "home/signup.html"
    form_class = SignUpForm
    #success_url = reverse_lazy("home:index")

    def form_valid(self, form):
        user = form.save()
        username = form.cleaned_data.get("username")
        password1 = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password1)
        if user is not None:
            login(self.request, user)
        return HttpResponseRedirect(self.get_success_url(), user.id)

    def get_success_url(self) -> str:
        pk = self.kwargs[pk]
        return reverse("home:detail_userprofile", kwargs={"pk": pk})    




class CreateUserProfile(LoginRequiredMixin, generic.CreateView):
    template_name = "home/user_profile.html"
    model = UserProfile
    form_class = UserProfileForm
    success_url = reverse_lazy("home:user_profile")
    login_url = "/"




class DetailUserProfile(LoginRequiredMixin, generic.View):
    template_name = "home/detail_userprofile.html"
    context = {}
    login_url = "/"

    def get(self, request, pk):
        self.context = {
            "profile": UserProfile.objects.get(id=pk)
        }
        return render(request, self.template_name,self.context)



class UpdateUserProfile(LoginRequiredMixin, generic.UpdateView):
    template_name = "home/update_userprofile.html"
    model = UserProfile
    form_class = UserProfileForm
    success_url = reverse_lazy("home:detail_userprofile")
    login_url = "/"

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("home:detail_userprofile", kwargs={"pk":pk})




class About(generic.View):
    template_name = "home/about.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Ray Parra"
        }
        return render(request, self.template_name, self.context)


class Identity(generic.View):
    template_name = "home/identity.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Ray Parra"
        }
        return render(request, self.template_name, self.context)


class Contact(generic.View):
    template_name = "home/contact.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Ray Parra"
        }
        return render(request, self.template_name, self.context)

templates/home/about.html
{% extends "base/base.html" %}




{% block title %} About View {% endblock title %}

{% block content %}
    <h1>Hola {{ name }} Bienvido a About XD</h1>
    <button class="btn btn-outline-danger">Test Bootstrap</button>
{% endblock content %}

templates/home/contact.html
{% extends "base/base.html" %}




{% block title %} Contact View {% endblock title %}

{% block content %}
    <h1>Hola {{ name }} Bienvido a Contact XD</h1>
    <button class="btn btn-outline-danger">Test Bootstrap</button>
{% endblock content %}

templates/home/detail_userprofile.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL USER PROFILE VIEW
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ profile.user.first_name }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the {{ profile.user.first_name }} profile.</strong> <br>
           {{ profile.user.first_name }} Bio: {{ profile.bio }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          {{ profile.user.first_name }} TimeStamp.
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the timestamp for {{ profile.user.first_name }} user. TimeStamp: {{ profile.timestamp}} </strong> 
          This Profile was Updated: {{ profile.updated }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Profile Status
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the status for {{ profile.user.first_name }}. Status: {{ profile.status }} </strong> 
        </div>
      </div>
    </div>
  </div>
  <a href="{% url 'home:update_userprofile' profile.id %}" class="btn btn-outline-warning">Update User Profile</a>
{% endblock content %}

templates/home/identity.html
{% extends "base/base.html" %}




{% block title %} Identity View {% endblock title %}

{% block content %}
    <h1>Hola {{ name }} Bienvido a Identity XD</h1>
    <button class="btn btn-outline-danger">Test Bootstrap</button>
{% endblock content %}

templates/home/index.html
{% extends "base/base.html" %}




{% block title %} Index View {% endblock title %}

{% block content %}
    {% if request.user.is_authenticated %}
    <a href="{% url 'home:logout' %}" class="btn btn-link">LogOut</a>
        <h1>Hola {{ request.user }} Bienvido a Django XD</h1>
        <button class="btn btn-outline-danger">Test Bootstrap</button>
        <br>
        <br><br>
        <br><br>
        <br>
        <br>
        <table class="table">
            {% for i in name %}
            <tr>
                <td>{{ name }}</td>
                <td>{{ name }}</td>
                <td>1289</td>
            </tr>  
            {% endfor %}
        </table>
    {% else %}
        <form action="" method="post">
            {% csrf_token %}
                {{ form }}
                <br><hr>
                <button type="submit" class="btn btn-outline-success">LogIn</button>
                <br>
        </form>
        <p>
            Si no tienes una cuenta registrate <a href="{% url 'home:signup' %}" class="btn btn-link">aqui</a>
        </p>
    {% endif %}    
    
{% endblock content %}

templates/home/signup.html
{% extends "base/base.html" %}

{% block title %}
  SIGNUP VIEW
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success form-control">Create a New User</button>
        <a href="{% url 'home:index' %}" class="btn btn-outline-warning form-control">Cancel</a>
  </form>
{% endblock content %}

templates/home/update_userprofile.html
{% extends "base/base.html" %}

{% block title %}
  UPDATE USER PROFILE VIEW
{% endblock title %}

{% block content %}
   <form action="" method="post" class="form">
    {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success form-control">Update User Profile</button>
        <a href="{% url 'home:detail_userprofile' request.user.id %}" class="btn btn-outline-warning form-control">Cancel</a>
   </form>
{% endblock content %}