api/urls.py
from django.urls import path
from api import views



app_name = "api"


urlpatterns = [
    path('v2/list/grantgoal/', views.GrantGoalAPIView.as_view(), name="api_list_grantgoal"),
    path('v2/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name="api_detail_grantgoal"),
    path('v2/create/grantgoal/', views.CreateGrantGoalAPIView.as_view(), name="api_create_grantgoal"),
    

    ##### URLS CLIENTS #####
    path('client/list/grantgoal/', views.ListGrantGoalClient.as_view(), name="clist_grantgoal"),
    path('client/create/grantgoal/', views.CreateGrantGoalClient.as_view(), name="ccreate_grantgoal"),
]

cplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

api/models.py
from django.db import models

# Create your models here.

api/forms.py
from django import forms

from core.models import GrantGoal

class CreateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = "__all__"
        exclude = ["timestamp", "final_date"]
        widgets = {
            "user": forms.Select(attrs={"type":"select","class":"form-select"}),
            "gg_title": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del GrantGoal"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"Escribe la descripcion del GrantGoal"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox", "class":"form-checkbox"}),
            "state": forms.Select(attrs={"type":"select","class":"form-select"}),
            "sprint":forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "slug":forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el codigo del GrantGoal"}),
        }

api/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import generic

from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import GrantGoalSerializer
from core.models import GrantGoal
from .forms import CreateGrantGoalForm



class GrantGoalAPIView(generics.ListAPIView):
    queryset = GrantGoal.objects.filter(status=True)
    serializer_class = GrantGoalSerializer


class DetailGrantGoalAPIView(APIView):

    def get(self, request, pk):
        queryset = GrantGoal.objects.get(pk=pk)
        data = GrantGoalSerializer(queryset).data
        return Response(data)



class CreateGrantGoalAPIView(generics.CreateAPIView):
    serializer_class = GrantGoalSerializer





#### CLIENTS ####


import requests

class ListGrantGoalClient(generic.View):
    template_name = "api/clist_grantgoal.html"
    context = {}
    url_api = "http://localhost:8000/api/v2/list/grantgoal/"

    def get(self, request):
        response = requests.get(url=self.url_api)
        self.context = {
            "grantgoals": response.json()
        }
        return render(request, self.template_name, self.context)



class CreateGrantGoalClient(generic.View):
    template_name = "api/ccreate_grantgoal.html"
    context = {}
    url_api = "http://localhost:8000/api/v2/create/grantgoal/"
    response = None
    payload = {}
    form_class = CreateGrantGoalForm

    def get(self, request):
        self.context = {
            "form": self.form_class
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request, *args, **kwargs):
        self.payload = {                     
            "gg_title": request.POST["gg_title"],
            "description": request.POST["description"],
            "days_duration": request.POST["days_duration"],
            "status": request.POST["status"],
            "state": request.POST["state"],
            "sprint": request.POST["sprint"],
            "slug": request.POST["slug"],
            "user": request.POST["user"]
        }
        self.response = requests.post(url=self.url_api, data=self.payload)
        return redirect("api:clist_grantgoal")

templates/api/ccreate_grantgoal.html
{% extends "base/base.html" %}

{% block title %}
  CREATE GRANT GOAL VIEW CLIENT
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Create GrantGoal</button>
        <a href="{% url 'api:api_list_grantgoal' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/api/clist_grantgoal.html
{% extends "base/base.html" %}

{% block title %}
  LIST GRANT GOAL CLIENT VIEW
{% endblock title %}

{% block content %}
  <table class="table">
    <thead>
        <th>ID</th>
        <th>GOAL TITLE</th>
        <th>USER</th>
        <th>TIMESTAMP</th>
        <th>STATUS</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
    </thead>
    <tbody>
        {% for gg in grantgoals %}
            <tr>
                <td>{{ gg.id }}</td>
                <td>{{ gg.gg_title }}</td>
                <td>{{ gg.user }}</td>
                <td>{{ gg.timestamp }}</td>
                <td>{{ gg.status }}</td>
                <td><a href="">Detail</a></td>
                <td><a href="">Update</a></td>
                <td><a href="">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
  </table>
{% endblock content %}